name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-22.04
    steps:
      - name: print greeting 
        run: echo 'hello world'
      - name: print goodby
        run: echo 'goodby'
        
